server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate,dialect=org.hibernate.dialect.PostgreSQLDialect


#Api Info
api.info.title=Picture Service
api.info.description=Creates, Stores And Get Pictures
api.info.version=1.0.0
api.info.contact-name=CHUKS
api.info.contact-url=www.chuks.com
api.info.contact-email=nwajeigoddowell@gmail.com

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.show-actuator=true


management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always
management.endpoints.web.exposure.include=refresh,health-

#POPULATING CONFIG
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
